import { query } from '@angular/animations';
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnDestroy, OnInit, inject } from '@angular/core';

import { FsMessage } from '@firestitch/message';
import { ObjectClasses } from 'playground/app/consts/object-classes.const';
import { of } from 'rxjs';
import { FsAuditsComponent } from '../../../../src/app/modules/audits/components/audits/audits.component';


@Component({
    selector: 'app-audits',
    templateUrl: './audits.component.html',
    styleUrls: ['./audits.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
    standalone: true,
    imports: [FsAuditsComponent],
})
export class AuditsComponent {
  private _message = inject(FsMessage);
  private _cdRef = inject(ChangeDetectorRef);


  public ObjectClasses = ObjectClasses;

  public loadAudits = (query) => {
    return of({
        "paging": {
            "limit": 25,
            "offset": 0,
            "records": 2
        },
        "audits": [
            {
                "id": 16864,
                "actorAccountId": 1,
                "subjectObjectId": 14001,
                "date": "2023-06-20T16:56:04+00:00",
                "auditMetas": [
                    {
                        "id": 116674,
                        "auditId": 16864,
                        "objectId": null,
                        "action": "info",
                        "name": "Type: account. Value: 123 sd. Privilege: Approver",
                        "property": null,
                        "value": "Added Object Contact",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": null,
                        "data": {}
                    },
                    {
                        "id": 116675,
                        "auditId": 16864,
                        "objectId": 14001,
                        "action": "change",
                        "name": " Client  Po",
                        "property": "clientPo",
                        "value": "2023-05-11",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    }
                ],
                "state": "active",
                "actorAccount": {
                    "id": 1,
                    "state": "active",
                    "guid": "58d507bf49e42241429bf4c7003d56b3",
                    "address": null,
                    "email": "admin@admin.com",
                    "firstName": "Firestitch",
                    "lastName": "Administrator",
                    "phone": null,
                    "name": "Firestitch Administrator",
                    "createDate": "2019-09-06T18:07:40+00:00",
                    "signinDate": "2023-06-20T10:28:38+00:00",
                    "imageType": "custom",
                    "avatar": {
                        "id": 1,
                        "abbreviation": null,
                        "color": "#31e620",
                        "small": "https://firestitch-dev.s3.amazonaws.com/pub/av/small/45f292dcc98afd37a92d6d519fac4088_1679141368.png",
                        "tiny": "https://firestitch-dev.s3.amazonaws.com/pub/av/tiny/45f292dcc98afd37a92d6d519fac4088_1679141368.png"
                    },
                    "activateEmailDate": null,
                    "activateEmailMessage": null,
                    "lastDigestDate": null,
                    "activateDate": null,
                    "modifyDate": "2023-06-20T10:28:38+00:00",
                    "passwordChange": false,
                    "digestDate": null,
                    "digestFrequency": "1",
                    "timezone": "Europe/Kiev",
                    "apiKey": null,
                    "apiSecret": null,
                    "type": "staff",
                    "approvalNotificationSchedule": [],
                    "orderReportNotificationSchedule": [
                        "8",
                        "12",
                        "14",
                        "17"
                    ],
                    "invoiceReportNotificationSchedule": [
                        "8",
                        "14",
                        "17"
                    ],
                    "title": "CTO",
                    "signature": "https://firestitch-dev.s3.amazonaws.com/pub/as/cafa2d0af0ed6e4893786ba3d98fbffe_1653561098.svg",
                    "addressId": 2,
                    "imageAcronym": "FA",
                    "imageTime": 1678903179,
                    "activateEmailState": null,
                    "modifierAccountId": null,
                    "invoiceReportDate": "2021-08-02T21:00:16+00:00",
                    "orderReportDate": "2022-04-02T18:22:06+00:00",
                    "force2fa": false
                },
                "subjectObject": {
                    "id": 14001,
                    "class": "work_order_one_time",
                    "subclass": null,
                    "className": "Work Order One Time",
                    "name": "T111-7",
                    "imageUrl": null,
                    "modifyDate": "2023-06-20T16:56:04+00:00",
                    "createDate": "2023-03-10T20:21:05+00:00",
                    "state": "active",
                    "meta": [],
                    "workspaceId": null,
                    "modifierAccount": null,
                    "creatorAccountId": null,
                    "modifierAccountId": 1,
                    "primaryKeyword": null,
                    "secondaryKeyword": null,
                    "parentObjectId": null,
                    "identifierParentObjectId": null,
                    "clientAccountId": 609,
                    "areaId": 608,
                    "companyId": 478,
                    "clientAccount": {
                        "id": 609,
                        "areaId": 608,
                        "billingAddressId": 610,
                        "parentClientAccountId": null,
                        "name": "NS Dundas Housekeeping",
                        "companyId": 478,
                        "number": "222",
                        "startDate": "2020-01-01T00:00:00",
                        "union": null,
                        "billingAttention": "Nick Nova",
                        "invoiceDelivery": "email",
                        "options": {},
                        "note": "[]",
                        "state": "active",
                        "serviceLocation": "98 Niska Drive, Waterdown",
                        "identifier": "DD-222",
                        "sageIdentifier": null,
                        "modifyDate": "2020-06-26T13:15:58+00:00",
                        "website": null,
                        "modifierAccountId": 466,
                        "paymentTerms": null,
                        "interestOnOverdueInvoices": null,
                        "terminationTerms": null,
                        "additionalTermsAndConditions": "Not Applicable",
                        "taxExempt": null
                    }
                }
            },
            {
                "id": 16227,
                "actorAccountId": 1,
                "subjectObjectId": 613,
                "date": "2023-03-10T20:21:05+00:00",
                "auditMetas": [
                    {
                        "id": 113764,
                        "auditId": 16227,
                        "objectId": null,
                        "action": "add",
                        "name": "Notification Staff Member",
                        "property": null,
                        "value": "Firestitch Administrator",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": null,
                        "data": {}
                    },
                    {
                        "id": 113765,
                        "auditId": 16227,
                        "objectId": null,
                        "action": "add",
                        "name": "Notification Staff Member",
                        "property": null,
                        "value": "Wendy Gull",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": null,
                        "data": {}
                    },
                    {
                        "id": 113766,
                        "auditId": 16227,
                        "objectId": null,
                        "action": "info",
                        "name": "T57",
                        "property": null,
                        "value": "Copied from",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": null,
                        "data": {}
                    },
                    {
                        "id": 113767,
                        "auditId": 16227,
                        "objectId": 14001,
                        "action": "change",
                        "name": " Agreement ",
                        "property": "agreementId",
                        "objectName": "Hello!",
                        "value": "14002",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113768,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Guid",
                        "property": "guid",
                        "value": "e3960a7d4b643d125ac59b7fd5fa475c",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113769,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Service  Description",
                        "property": "serviceDescription",
                        "value": "Services performed {$original_billing_month}",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113770,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Creator  Account ",
                        "property": "creatorAccountId",
                        "value": "1",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113771,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Bill  Batch",
                        "property": "billBatch",
                        "value": "Null",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113772,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Identifier",
                        "property": "identifier",
                        "value": "T111-7",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113773,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " State",
                        "property": "state",
                        "value": "Open",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113774,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Modifier  Account ",
                        "property": "modifierAccountId",
                        "value": "1",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113775,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Pay  Period  Number",
                        "property": "payPeriodNumber",
                        "value": "Null",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113776,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Pay  Period  From  Date",
                        "property": "payPeriodFromDate",
                        "value": "Null",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113777,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Pay  Period  To  Date",
                        "property": "payPeriodToDate",
                        "value": "Null",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113778,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Pay  Period  Year",
                        "property": "payPeriodYear",
                        "value": "Null",
                        "valueObjectId": null,
                        "valueType": "string",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113779,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Billing  Month",
                        "property": "billingMonth",
                        "value": "2023-03-10",
                        "valueObjectId": null,
                        "valueType": "date",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113780,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Original  Billing  Month",
                        "property": "originalBillingMonth",
                        "value": "2023-03-10",
                        "valueObjectId": null,
                        "valueType": "date",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    },
                    {
                        "id": 113781,
                        "auditId": 16227,
                        "objectId": 14001,
                        "objectName": "Hello!",
                        "action": "change",
                        "name": " Number",
                        "property": "number",
                        "value": "1117",
                        "valueObjectId": null,
                        "valueType": "number",
                        "subject": null,
                        "objectClass": "work_order_one_time",
                        "data": {}
                    }
                ],
                "state": "active",
                "actorAccount": {
                    "id": 1,
                    "state": "active",
                    "guid": "58d507bf49e42241429bf4c7003d56b3",
                    "address": null,
                    "email": "admin@admin.com",
                    "firstName": "Firestitch",
                    "lastName": "Administrator",
                    "phone": null,
                    "name": "Firestitch Administrator",
                    "createDate": "2019-09-06T18:07:40+00:00",
                    "signinDate": "2023-06-20T10:28:38+00:00",
                    "imageType": "custom",
                    "avatar": {
                        "id": 1,
                        "abbreviation": null,
                        "color": "#31e620",
                        "small": "https://firestitch-dev.s3.amazonaws.com/pub/av/small/45f292dcc98afd37a92d6d519fac4088_1679141368.png",
                        "tiny": "https://firestitch-dev.s3.amazonaws.com/pub/av/tiny/45f292dcc98afd37a92d6d519fac4088_1679141368.png"
                    },
                    "activateEmailDate": null,
                    "activateEmailMessage": null,
                    "lastDigestDate": null,
                    "activateDate": null,
                    "modifyDate": "2023-06-20T10:28:38+00:00",
                    "passwordChange": false,
                    "digestDate": null,
                    "digestFrequency": "1",
                    "timezone": "Europe/Kiev",
                    "apiKey": null,
                    "apiSecret": null,
                    "type": "staff",
                    "approvalNotificationSchedule": [],
                    "orderReportNotificationSchedule": [
                        "8",
                        "12",
                        "14",
                        "17"
                    ],
                    "invoiceReportNotificationSchedule": [
                        "8",
                        "14",
                        "17"
                    ],
                    "title": "CTO",
                    "signature": "https://firestitch-dev.s3.amazonaws.com/pub/as/cafa2d0af0ed6e4893786ba3d98fbffe_1653561098.svg",
                    "addressId": 2,
                    "imageAcronym": "FA",
                    "imageTime": 1678903179,
                    "activateEmailState": null,
                    "modifierAccountId": null,
                    "invoiceReportDate": "2021-08-02T21:00:16+00:00",
                    "orderReportDate": "2022-04-02T18:22:06+00:00",
                    "force2fa": false
                },
                "subjectObject": {
                    "id": 613,
                    "class": "work_order_one_time",
                    "subclass": null,
                    "className": "Work Order One Time",
                    "name": "T57",
                    "imageUrl": null,
                    "modifyDate": "2023-01-19T17:49:25+00:00",
                    "createDate": "2020-01-31T20:42:29+00:00",
                    "state": "active",
                    "meta": [],
                    "workspaceId": null,
                    "modifierAccount": null,
                    "creatorAccountId": null,
                    "modifierAccountId": 603,
                    "primaryKeyword": null,
                    "secondaryKeyword": null,
                    "parentObjectId": null,
                    "identifierParentObjectId": null,
                    "clientAccountId": 609,
                    "areaId": 608,
                    "companyId": 478,
                    "clientAccount": {
                        "id": 609,
                        "areaId": 608,
                        "billingAddressId": 610,
                        "parentClientAccountId": null,
                        "name": "NS Dundas Housekeeping",
                        "companyId": 478,
                        "number": "222",
                        "startDate": "2020-01-01T00:00:00",
                        "union": null,
                        "billingAttention": "Nick Nova",
                        "invoiceDelivery": "email",
                        "options": {},
                        "note": "[]",
                        "state": "active",
                        "serviceLocation": "98 Niska Drive, Waterdown",
                        "identifier": "DD-222",
                        "sageIdentifier": null,
                        "modifyDate": "2020-06-26T13:15:58+00:00",
                        "website": null,
                        "modifierAccountId": 466,
                        "paymentTerms": null,
                        "interestOnOverdueInvoices": null,
                        "terminationTerms": null,
                        "additionalTermsAndConditions": "Not Applicable",
                        "taxExempt": null
                    }
                }
            }
        ]
    });
}
}
