export enum ObjectClass {
  WorkOrderOneTime = 'work_order_one_time',
  WorkOrderRecurring = 'work_order_recurring',
  WorkOrderTemplate = 'work_order_template',
  Account = 'account',
  Invoice = 'invoice',
  Area = 'area',
  Company = 'company',
  Contract = 'contract',
  Product = 'product',
  Region = 'region',
  PurchaseOrder = 'pruchase_order',
  ClientAccount = 'client_account',
  Vendor = 'vendor',
  Type = 'type',
  Status = 'status',
  Category = 'category',
  Address = 'address',
  Asset = 'asset',
  Image = 'image'
}
